package com.bergerlavy.bolepo;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.HashMap;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import android.content.ContentResolver;
import android.content.ContentUris;
import android.content.Context;
import android.content.SharedPreferences;
import android.content.res.AssetFileDescriptor;
import android.database.Cursor;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.net.Uri;
import android.provider.ContactsContract;
import android.provider.ContactsContract.Contacts;

import com.bergerlavy.bolepo.dals.Meeting;
import com.bergerlavy.bolepo.forms.BolePoContact;
import com.bergerlavy.bolepo.forms.CreateMeetingValidation;
import com.bergerlavy.bolepo.forms.InputValidationReport;
import com.bergerlavy.bolepo.forms.ModifyMeetingValidation;
import com.google.android.gms.maps.model.LatLng;

public class BolePoMisc {

	/* SharedPreferences */
	public static final String GENERAL_PREFERENCES = "GENERAL_PREFERENCES";

	/* key-value pairs in SharedPreferences */
	public static final String GENERAL_PREFS_DEVICE_PHONE_NUMBER = "GENERAL_PREFS_DEVICE_PHONE_NUMBER";
	public static final String GENERAL_PREFS_GCM_REGISTRATION_ID = "GENERAL_PREFS_GCM_REGISTRATION_ID";

	/**
	 * Returns the device phone number.
	 * @param context required to get the SharedPreferences instance.
	 * @return the phone number the user entered the first time he/she started the application.
	 */
	public static String getDevicePhoneNumber(Context context) {
		SharedPreferences generalPrefs = context.getSharedPreferences(GENERAL_PREFERENCES, Context.MODE_PRIVATE);
		return generalPrefs.getString(GENERAL_PREFS_DEVICE_PHONE_NUMBER, "");
	}
	
	public static BolePoContact getDeviceUserAsBolePoContact(Context context) {
		return new BolePoContact.Builder("Me", getDevicePhoneNumber(context)).build();
	}

	public static void setDevicePhoneNumber(Context context, String phone) {
		SharedPreferences genePreferences = context.getSharedPreferences(GENERAL_PREFERENCES, Context.MODE_PRIVATE);
		SharedPreferences.Editor editor = genePreferences.edit();
		editor.putString(GENERAL_PREFS_DEVICE_PHONE_NUMBER, phone);
		editor.commit();
	}

	public static void setGcmRegId(Context context, String regId) {
		SharedPreferences generalPrefs = context.getSharedPreferences(GENERAL_PREFERENCES, Context.MODE_PRIVATE);
		SharedPreferences.Editor editor = generalPrefs.edit();
		editor.putString(GENERAL_PREFS_GCM_REGISTRATION_ID, regId);
		editor.commit();
	}

	public static void removeGcmId(Context context) {
		SharedPreferences generalPrefs = context.getSharedPreferences(GENERAL_PREFERENCES, Context.MODE_PRIVATE);
		SharedPreferences.Editor editor = generalPrefs.edit();
		editor.remove(GENERAL_PREFS_GCM_REGISTRATION_ID);
		editor.commit();
	}

	public static String chopeNonDigitsFromPhoneNumber(String phone) {
		String result = "";
		for (int i = 0 ; i < phone.length() ; i++)
			if (phone.charAt(i) >= '0' && phone.charAt(i) <= '9')
				result += phone.charAt(i);
		return result;
	}

	/**
	 * Checks if the device is connected to the internet.
	 * @param context A context to use to get a reference to the ConnectivityManager.
	 * @return <code>true</code> if the device is connected to the internet, <code>false</code> otherwise.
	 */
	public static boolean isDeviceOnline(Context context) {
		ConnectivityManager cm = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
		NetworkInfo netInfo = cm.getActiveNetworkInfo();
		/* if the device is in airplane mode (or presumably in other situations where there's no available network)
		 * the function "getActiveNetworkInfo" will return null - hence the checking for null */
		if (netInfo != null && netInfo.isConnectedOrConnecting())
			return true;
		return false;
	}

	public static InputValidationReport createMeetingInputValidation(Context context, Meeting data) {
		CreateMeetingValidation vStatus = new CreateMeetingValidation(context, data);
		return vStatus.isOK();
	}

	public static InputValidationReport modifyMeetingInputValidation(Context context, Meeting data, long id) {
		ModifyMeetingValidation vStatus = new ModifyMeetingValidation(context, data, id);
		return vStatus.isOK();
	}

	/* reading the contacts that are registered to the application from a file generated by the 
	 * contacts service */
	public static HashMap<Long, String> readContacts(Context context) {
		HashMap<Long, String> contacts = new HashMap<Long, String>();
		
		try {
			FileInputStream fis = context.openFileInput(BolePoConstants.CONTACTS_FILE_NAME);
			String id;
			String phone;
			while (!((id = readNameFromFile(fis)).equalsIgnoreCase(""))) {
				phone = readPhoneFromFile(fis);
				contacts.put(Long.parseLong(id), phone);
			}
			fis.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return contacts;
	}
	
	private static String readNameFromFile(FileInputStream fis) throws IOException {
		String name = "";
		char c, d, e;
		int x;
		while ((x = fis.read()) != -1) {
			c = (char) x;
			if (c != '#')
				name += c;
			else {
				x = fis.read();
				d = (char) x;
				if (d != -1) {
					if (d != '@') {
						name += d;
					}
					else {
						x = fis.read();
						e = (char) x;
						if (e != -1) {
							if (e != '%') {
								name += e;
							}
							else {
								break;
							}
						}
					}
				}
			}
		}
		return name;
	}

	private static String readPhoneFromFile(FileInputStream fis) throws IOException {
		String phone = "";
		char c, d, e;
		int x;
		while ((x = fis.read()) != -1) {
			c = (char) x;
			if (c != '%')
				phone += c;
			else {
				x = fis.read();
				d = (char) x;
				if (d != -1) {
					if (d != '@') {
						phone += d;
					}
					else {
						x = fis.read();
						e = (char) x;
						if (e != -1) {
							if (e != '#') {
								phone += e;
							}
							else {
								break;
							}
						}
					}
				}
			}
		}
		return phone;
	}

	
	public static ArrayList<LatLng> geocoding(String address) throws IOException, JSONException {
		address = URLEncoder.encode(address, "UTF-8");
		URL url = new URL("http://maps.googleapis.com/maps/api/geocode/json?" +
				"address=" + address + "&sensor=true");
		
		URLConnection connection = url.openConnection();
		connection.setDoOutput(true);
		connection.setConnectTimeout(10000000);
		String line;
		StringBuilder builder = new StringBuilder();
		BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
		while ((line = reader.readLine()) != null) {
			builder.append(line);
		}
		reader.close();
		ArrayList<LatLng> coordinates = new ArrayList<LatLng>();
		JSONObject json = new JSONObject(builder.toString());
		if (json.getString("status").equalsIgnoreCase("ok") == true) {
			JSONArray results = json.getJSONArray("results");
			if (results != null) {
				JSONObject firstResult = results.getJSONObject(0);
				JSONObject geometry = firstResult.getJSONObject("geometry");
				if (geometry != null) {
					JSONObject bounds = geometry.getJSONObject("bounds");
					if (bounds != null) {
						JSONObject northeast = bounds.getJSONObject("northeast");
						JSONObject southwest = bounds.getJSONObject("southwest");
						if (northeast != null && southwest != null) {
							coordinates.add(new LatLng(northeast.getDouble("lat"), northeast.getDouble("lng")));
							coordinates.add(new LatLng(southwest.getDouble("lat"), southwest.getDouble("lng")));
						}
					}
					JSONObject location = geometry.getJSONObject("location");
					if (location != null) {
						coordinates.add(new LatLng(location.getDouble("lat"), location.getDouble("lng"))); 
					}
				}
			}
		}

		return coordinates;
	}
	
	public static String getBolePoContactName(Context context, Long contactId) {
		String name = "";
		ContentResolver cr = context.getContentResolver();
		Cursor c = cr.query(ContactsContract.Data.CONTENT_URI,
				new String[] { ContactsContract.CommonDataKinds.StructuredName.DISPLAY_NAME_PRIMARY },
				ContactsContract.Data.RAW_CONTACT_ID + " = " + contactId + " and " +
				ContactsContract.Data.MIMETYPE + " = '" + ContactsContract.CommonDataKinds.StructuredName.CONTENT_ITEM_TYPE + "'",
				null, null);
		
		if (c != null) {
			if (c.moveToFirst()) {
				name = c.getString(c.getColumnIndex(ContactsContract.CommonDataKinds.StructuredName.DISPLAY_NAME_PRIMARY));
			}
		}
		return name;
	}
	
	public static String getBolePoContactPhone(Context context, Long contactId) {
		String phone = "";
		ContentResolver cr = context.getContentResolver();
		Cursor c = cr.query(
				ContactsContract.CommonDataKinds.Phone.CONTENT_URI,
				null,
				ContactsContract.CommonDataKinds.Phone.CONTACT_ID + " = " + contactId,
				null, null);
		if (c != null) {
			if (c.moveToFirst()) {
				phone = c.getString(c.getColumnIndex(ContactsContract.CommonDataKinds.Phone.NUMBER));
				phone = chopeNonDigitsFromPhoneNumber(phone);
			}
		}
		return phone;
	}
	
	public static Bitmap getBolePoContactThumbnail(Context context, String phone) {
		Bitmap thumbnail = null;
		ContentResolver cr = context.getContentResolver();
		Uri uri = Uri.withAppendedPath(ContactsContract.CommonDataKinds.Phone.CONTENT_FILTER_URI, Uri.encode(phone));
		Cursor c = cr.query(
				uri,
				new String[] { ContactsContract.Contacts.PHOTO_ID },
				null, null,
				ContactsContract.Contacts.DISPLAY_NAME + " ASC");
		if (c != null) {
			if (c.moveToFirst()) {
				int thumbnailId;
				thumbnailId = c.getInt(c.getColumnIndex(ContactsContract.Contacts.PHOTO_ID));
				c.close();
				uri = ContentUris.withAppendedId(ContactsContract.Data.CONTENT_URI, thumbnailId);
				c = cr.query(uri, new String[] { ContactsContract.CommonDataKinds.Photo.PHOTO }, null, null, null);
				if (c != null) {
					if (c.moveToFirst()) {
						byte[] thumbnailBytes = c.getBlob(0);
						if (thumbnailBytes != null) {
							thumbnail = BitmapFactory.decodeByteArray(thumbnailBytes, 0, thumbnailBytes.length);
						}
					}
				}
			}
			c.close();
		}
		return thumbnail;
	}
	
	public static Bitmap getBolePoContactPhoto(Context context, Long contactId) {
		Uri contactUri = ContentUris.withAppendedId(Contacts.CONTENT_URI, contactId);
		Uri displayPhotoUri = Uri.withAppendedPath(contactUri, Contacts.Photo.DISPLAY_PHOTO);
		AssetFileDescriptor fd = null;
		try {
			fd = context.getContentResolver().openAssetFileDescriptor(displayPhotoUri, "r");
			return BitmapFactory.decodeStream(fd.createInputStream());
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}
}
